export type cigarItem = {
  id: number;
  cigarName: string;
  drawRating: number;
  appearanceRating: number;
  burnRating: number;
  aromaRating: number;
  tasteRating: number;
  smokeTime: number;
  review: string;
  image: string;
  blend?: string;
  visualNotes?: string;
  coldDraw?: string;
  firstThird?: string;
  secondThird?: string;
  lastThird?: string;
  smokingDuration?: string;
  construction?: string;
  formType: "advanced" | "basic";
};
